
services:
  cms:
    build: .
    environment:
      CMS_SERVER_TOKEN: ${CMS_SERVER_TOKEN} 
      CMS_PORT: 8001 
    volumes:
      - ./www:/www
      - ./content:/content
    ports:
      - 8001:8001

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/srv/www 
    ports:
      - 8000:80
